[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "gst-python-ml"
version = "0.3.0"
description = "Your project description"
readme = "README.md"
requires-python = "==3.13.*"
dependencies = [
    "pygobject",
    "torch",
    "torchvision",
    "torchaudio",
    "transformers==4.48",
    "numpy",
    "huggingface-hub",
    "lap",
    "pycairo",
    "ultralytics",
    "bitsandbytes",
    "pytest>=7.0",
    "confluent_kafka",
    # flash-attn might need to be manually installed
    #"flash-attn",
    "diffusers",
    "sentencepiece",
    "protobuf",
    "accelerate",
    "pysilero",
    "faster_whisper",
    "pysilero-vad",
    "whisperspeech",
    "webdataset",
    "easydict",
    "pyflann-py3"
]
